# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['GPO Santa V2.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'ultralytics',
        'ultralytics.nn',
        'ultralytics.nn.modules',
        'ultralytics.models',
        'ultralytics.models.yolo',
        'ultralytics.utils',
        'ultralytics.data',
        'torch',
        'torchvision',
        'cv2',
        'PIL',
        'PIL._tkinter_finder',
        'numpy',
        'mss',
        'pydirectinput',
        'keyboard',
        'pynput',
        'pynput.keyboard',
        'pynput.mouse',
        'pygetwindow',
        'win32api',
        'win32con',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='GPO Santa V2',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
